application: jwchack
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /tasks/work
  script: work.py

- url: /.*
  script: main.app